# NBA API Configuration
nba_api:
  rate_limit_delay: 1  # seconds between requests
  retry_attempts: 3
  timeout: 30

# Model Configuration
model:
  path: "../nba-predictions-model/xgb_pipeline.pkl"
  version: "1.0"
  feature_version: "1.0"

# Database Configuration
database:
  path: "../nba-predictions-api/data/nba_predictions.db"
  backup_enabled: true
  backup_path: "./backups/"

# Prediction Configuration
prediction:
  confidence_thresholds:
    high: 0.8
    medium: 0.6
  default_date_offset: -1  # days (yesterday)

# Logging Configuration
logging:
  level: "INFO"
  file_path: "./logs/scheduler.log"
  max_file_size: "10MB"
  backup_count: 5